spring.application.name=final-1

server.port=9999

spring.datasource.url=jdbc:oracle:thin:@nam3324.synology.me:32800:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=C##KH_JAVA_FINAL_1
spring.datasource.password=123456

mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.kh.dto

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

jwt.secret=0173d9ef712e1eae6ce27742f59fa35df08198d0e7f10c130e70375ea2fba6fe7eaf228882cc2d9f194e14c8e8002124ba3e50b213e8a5cee3dcbe5d36e7b2f8
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=14400000

cors.allowed-origin=http://localhost:3000

google.genai.api-key=AIzaSyC-ONwVEsSk1q3EmyWA7kwHE7r2GJ3jfNI

weather.api.key=fe9260600c75e0a14530ddb5cb7e1c0e838815f98e921f0d9104ea6ba457e0c7
weather.location.seoul.nx=60
weather.location.seoul.ny=127

seoul.api.key=666b5271496f6e733834427a4d6b50

tmdb.api.key=674c3b16235176789e8ad2f9fee1a760
naver.api.client-id=Xdy0nX4rvj4mCo7BTp3H
naver.api.client-secret=4KJyMrxic9

