// src/main/java/com/kh/dto/EventDto.java
package com.kh.dto;

import lombok.*;
import java.time.LocalDate;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class EventDto {
    private Long id;           // 내부 증가 ID
    private String title;      // culutename / title / name ...
    private String place;      // cultureaddress / address ...
    private String gu;         // district / gu ...
    private String category;   // category

    private LocalDate dateStart; // startdate / start_date / sdate ...
    private LocalDate dateEnd;   // enddate / end_date / edate ...
    private String time;         // (CSV에 없으면 "")

    private String thumbUrl;     // thumbnailimage / image / thumb ...
    private String fee;          // fee
    private String audience;     // targetaudience / audience ...
    private String host;         // organizationname / host ...
    private String address;      // cultureaddress
    private String url;          // portalurl / url / link ...
    private String description;  // description / desc ...
    private Boolean isFree;      // isfree == "무료"/true/1/Y/예

    private Double lat;          // 확장
    private Double lng;          // 확장
}
